name: Webhook Notification Workflow

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on PR to main branch

jobs:
  send-webhook:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send Webhook Notification
        if: always()  # Send webhook even if the job fails
        run: |
          curl -X POST ${{ secrets.WEBHOOK_URL }} \
          -H "Content-Type: application/json" \
          -d '{
            "incident-description": "GitHub workflow triggered for repository: ${{ github.repository }}",
            "user": "${{ github.actor }}",
            "severity": "${{ job.status == 'success' && 'low' || 'high' }}"
          }'
