name: Webhook Notification Workflow

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on PR to main branch

jobs:
  send-webhook:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up date and commit details
        id: set_details
        run: |
          export RECENT_COMMIT_HASH="$(git show --format="%H" -s)"
          export RECENT_COMMIT_DATE="$(git show --format="%cD" -s)"
          export RECENT_COMMIT_TITLE="$(git show --format="%s" -s)"
          export RECENT_COMMIT_AUTHOR_NAME="$(git show --format="%an" -s)"
          export RECENT_COMMIT_AUTHOR_EMAIL="$(git show --format="%ae" -s)"
          export WORKFLOW_RUN_ID="${{ github.run_id }}"
          export WORKFLOW_NAME="${{ github.workflow }}"
          echo "recent_commit_hash=$RECENT_COMMIT_HASH" >> $GITHUB_ENV
          echo "recent_commit_date=$RECENT_COMMIT_DATE" >> $GITHUB_ENV
          echo "recent_commit_title=$RECENT_COMMIT_TITLE" >> $GITHUB_ENV
          echo "recent_commit_author_name=$RECENT_COMMIT_AUTHOR_NAME" >> $GITHUB_ENV
          echo "recent_commit_author_email=$RECENT_COMMIT_AUTHOR_EMAIL" >> $GITHUB_ENV
          echo "workflow_run_id=$WORKFLOW_RUN_ID" >> $GITHUB_ENV
          echo "workflow_name=$WORKFLOW_NAME" >> $GITHUB_ENV

      - name: Send Webhook Notification (Slack)
        if: always()  # Send webhook even if the job fails
        run: |
          curl -X POST ${{ secrets.SLACK_WEBHOOK_URL }} \
          -H "Content-Type: application/json" \
          -d '{
            "text": "GitHub Workflow Details",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Workflow Run ID:* ${{ env.workflow_run_id }}\n*Workflow Name:* ${{ env.workflow_name }}\n*Commit Hash:* ${{ env.recent_commit_hash }}\n*Commit Author:* ${{ env.recent_commit_author_name }}\n*Commit Date:* ${{ env.recent_commit_date }}\n*Commit Title:* ${{ env.recent_commit_title }}"
                }
              }
            ]
          }'
