name: Send HTML File to Slack

on:
  push:
    branches:
      - main

jobs:
  notifySlack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read HTML content and send to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          HTML_CONTENT=$(cat index.html | sed 's/"/\\"/g' | tr '\n' ' ')
          curl -X POST "$WEBHOOK_URL" \
          -H 'Content-type: application/json' \
          --data '{
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*📄 index.html file pushed to main:*"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "```'"$HTML_CONTENT"'```"
                }
              }
            ]
          }'
