name: Send HTML Content to Slack

on:
  push:
    branches: [main]

jobs:
  notifySlack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read HTML content and send to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ WEBHOOK_URL }}
        run: |
          if [ -f "index.html" ]; then
            # Read and escape HTML content safely
            HTML_CONTENT=$(jq -Rs . < index.html)

            curl -X POST "$WEBHOOK_URL" \
            -H "Content-type: application/json" \
            --data "{
              \"blocks\": [
                {
                  \"type\": \"section\",
                  \"text\": {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*📄 index.html content:* \n\`\`\`$HTML_CONTENT\`\`\`\"
                  }
                }
              ]
            }"
          else
            echo "index.html not found"
          fi
